name: push readme

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push the readme to user profile
        uses: apgapg/copy_file_to_another_repo_action@dev/rename-destination-file
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          rename: 'colosseum-game.md'
          destination_repo: 'Saltyparts/Saltyparts.github.io'
          destination_folder: 'src'
          user_email: 'chaynabors@gmail.com'
          user_name: 'Saltyparts'
          commit_message: 'update colosseum-game readme'

